// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace toDoList.Models
{
    public partial class Users
    {
        public Users()
        {
            ToDoItem = new HashSet<ToDoItem>();
        }

        public int IdUser { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }

        public virtual ICollection<ToDoItem> ToDoItem { get; set; }
    }
}